<template>
	<layout title="Terms">
		<div class="px-4 py-6 md:py-16 relative">
			<div class="max-w-5xl mx-auto">
				<heading size="heading2" class="mb-10 text-center">Terms of Service</heading>
				<heading size="large" class="mb-3">General</heading>
				<p
					class="mb-2"
				>In terms of Information Technology statutes, this document is an electronic record. Being generated by a computer system it does not require any physical or digital signatures.</p>
				<p
					class="mb-2"
				>This document is published in accordance with the provisions of Information Technology regulations that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of:</p>
				<list
					unordered-list-color="text-blue-600"
					:lists="['You must read, agree with and accept all of the terms and conditions contained in this Agreement in order to use our Website located at Jobs harbour','The Website Jobs Harbour(hereinafter referred to as Jobs Harbour), owned by Sumato Globaltech Private Limited where such expression shall, unless repugnant to the context thereof, be deemed to include its respective legal heirs, representatives, administrators, permitted successors and assigns','By using the Website, You accept and agree to be bound by this Agreement, the Privacy Policy, as well as rules, guidelines, policies, terms and conditions applicable to any service that is provided by this Website, that shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use.']"
				></list>

				<heading size="large" class="mt-4 mb-3">Definitions</heading>
				<list
					unordered-list-color="text-blue-600"
					:lists="['We, us, our, jobs harbour shall mean Jobs Harbour the Website/the portal or the Company.','Agreement shall mean and refer to this Terms of Service, including any amendments that may be incorporated into it.','You or User shall mean any natural or legal person who has agreed to become a user of the Jobs Harbour Platform by signing up to the Website. The Jobs Harbour Platform also provides certain services without registration/acceptance, and such provision of services does not absolve you of this contractual relationship. This shall also include Organisers.','Customer shall mean any User who shall utilize the Jobs Harbour Platform to request for Services to be performed by any Organiser. From time to time, Jobs Harbour may act as a Plateform, and the terms and conditions of this Agreement applicable to Customers will apply to Jobs Harbour when acting in this way.','Organiser means any enterprise or individual User utilizing the Jobs Harbour Platform to offer Services to Customers.','Contract means a particular project or set of ongoing tasks for which a Customer has requested Services to be offered by a Organiser and the Organiser has offered on the Jobs Harbour Platform.','Third Party shall mean and refer to any individual(s), enterprise or entity apart from the Users and Jobs Harbour.','Services shall mean and refer to the services offered on the site including but not limited to recreational, sporting and leisure activities and communications related services.','Organiser Fees means a fixed fee which will be set by the Organiser for which the customer can avail the services offered and this fee will be non-negotiable.']"
				></list>

				<heading size="large" class="mt-4 mb-3">Online website platform</heading>
				<p>Jobs Harbour is an online platform where users can find Jobs, which shall include, but are not limited to setting out their preferences in relation to the activities they wish to partake in and Job seekers can apply. The Website works on the model of listing of Organisers and enabling them to showcase their profile. The Website also has a provision for the Users to provide their ratings and reviews on the quality of services. Job Harbour is a portal where the Organisers, both agencies and freelancers will claim their own work.</p>

				<heading size="large" class="mt-4 mb-3">Eligibility</heading>
				<p>The User represents and warrants that he/she is competent and eligible to enter into legally binding agreements and that he/she has the requisite authority to bind himself/herself to these Terms, as determined solely by the provisions of the Indian Contract Act, 1872. The User may not use the Jobs Harbour Platform if he/she is not competent to contract under the Indian Contract Act, 1872, or is disqualified from doing so by any other applicable law, rule or regulation currently in force.</p>

				<heading size="large" class="mt-4 mb-3">Content</heading>
				<p>All information provided by Job Creators are self-declared and not verified by Jobs Harbour. Any and all information posted by any Job Creator/Employer/agency including but not limited to their jobs, Jobs Harbour has the right to use this Content for promotions or marketing purposes.</p>

				<heading
					size="large"
					class="mt-4 mb-3"
				>Termination: The Company may terminate the Services in case the Subscriber:</heading>
				<list
					unordered-list-color="text-blue-600"
					:lists="['Commits any breach of these terms and condition, representation & warranties and Subscribers obligations as contemplated in this agreement.','Fails to make payments as per the terms & condition herein.','Uses the Services provided by the Company for any illegal, unlawful or immoral purposes or in any fraudulent manner or for purposes not authorized by the Company.','Advice received from regulatory or any other competent authorities.','Commits violation of any IPR, rights of privacy, rights of publicity and/or any other rights of third party and shall not be violative of any provision of Law in force.']"
				></list>

				<heading size="large" class="mt-4 mb-3">General Terms & Condition</heading>
				<list
					unordered-list-color="text-blue-600"
					:lists="['These job postings may not be substituted with other job postings during this term without incurring additional charges. Any jobs posted by Subscriber on the website and in excess of the number of jobs provided for in this Agreement will be billed to the Subscriber and shall be payable by the Subscriber in accordance with the terms hereof, at the Companys then prevailing rate for such job postings on the Website.','Any terms of this Agreement that may be invalid shall not affect the validity of enforcement of the remaining valid terms of this Agreement. The terms and conditions of this Agreement may not be amended without the affirmative written consent of Jobs Harbour.','The agreement shall be effective for the period as specified in the Customer Service Agreement Form. This agreement will be extended automatically for a further period of similar duration, unless otherwise specified or terminated by the Company or by the Subscriber through a written communication to the Company seeking withdrawal of services on or before atleast 1 week from the date of expiry of the agreement. The Company will accordingly raise an invoice basis the prices of services prevailing at the time of extension/renewal of this agreement and all other terms and conditions of the agreement shall remain unchanged.','The Company shall not refund or give a credit note or charge additional charges to the Subscriber in the event of change in the tariff plans which the Company may introduce from time to time.','The Terms & Conditions between the Subscriber & the Company shall be governed by the laws of India and any dispute or differences, if any between the Subscriber & the Company, shall be subject to the exclusive jurisdictions of the Guwahati High Court.']"
				></list>
			</div>
		</div>
	</layout>
</template>

<script>
import Layout from "@/Shared/Layout";
import Heading from "@/Shared/tuis/Heading";
import Icon from "@/Shared/tuis/Icon";
import LinkTo from "@/Shared/tuis/LinkTo";
import Card from "@/Shared/tuis/Card";
import List from "@/Shared/tuis/List";
import LoadingButton from "@/Shared/tuis/LoadingButton";

export default {
	components: {
		Layout,
		Heading,
		Icon,
		LinkTo,
		Card,
		List,
		LoadingButton
	}
};
</script>
